version: '3'
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.app.dev
    volumes:
      - ./:/express-dev
      - node-modules-data:/express-dev/node_modules
    command: sh -c "npm i & npm run start"
    ports:
      - 8080:8080
    working_dir: /express-dev
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.dev
    ports: 
      - 80:80
volumes:
  node-modules-data:
