version: '3'
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/express-dev
      - node-modules-data:/express-dev/node_modules
    command: sh -c "npm i & npm run start"
    ports:
      - 8080:8080
    working_dir: /express-dev
volumes:
  node-modules-data:
